server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sarah_voice_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        connection:
          characterEncoding: utf8
          useUnicode: true

  sql:
    init:
      mode: always

  application:
    name: sarah-assistente-virtual

  jackson:
    time-zone: America/Sao_Paulo

# Configurações adicionais importantes
logging:
  level:
    com.sarah: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE